### ISSUE TITLE
Incompatibilty of BYG Variant with newest 2.2.0 MCW Roofs Version

### ISSUE THREAD

**Issue by Beleggrodion** [Samlegamer/Macaw-s-Roofs-Compat#10]
When installed mcw-roofs-2.2.0-mc1.18.2-fabric.jar together with macawsroofsbyg-fabric-1.18.2-1.0.jar , this mod cause a minecraft startup crash. If i downgrade to mcw-roofs-2.1.2fabric-mc1.18.2.jar , minecraft start as it shoul'd. 

Is their a updated planned like the Biomes O' Plenty Variant has received?

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'macawsroofsbyg'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/kikoz/mcwroofs/objects/roofs/RoofBlock
	at fr.samlegamer.macawsroofsbyg.MacawsRoofsBYG.onInitialize(MacawsRoofsBYG.java:17)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.kikoz.mcwroofs.objects.roofs.RoofBlock
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more
```

**Comment by DaRealSparky** [comment]
So I think the mod file is miss-labeled. I'm using it on 1.18.2 Forge and it loads fine, albeit on the previous version of Macaw's Roofs. (2.1.2 at the time of writing)

Edit: Didn't see that it loaded fine on Fabric with Macaw's Roofs 2.1.2. Guess it's multi-modloader?

**Comment by Samlegamer** [comment]
fixed in new version
